# Generated by Django 3.2.9 on 2021-12-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        help_text="IP address of the visitor",
                        max_length=45,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "visit_time",
                    models.DateTimeField(verbose_name="Visit time", auto_now_add=True),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="links.link",
                        verbose_name="Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
                "ordering": ["visit_time"],
            },
        ),
    ]
